manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: core/hid-nkro-configurable-support
      revision: ble/hog-characteristic-perm-tweaks-macos
      import: app/west.yml
  self:
    path: config
